# Generated by Django 4.2.6 on 2023-10-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_productos_proveedor_resena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='categoria',
            new_name='producto_categoria',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='descripcion',
            new_name='producto_descripcion',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='producto_nombre',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='precio',
            new_name='producto_precio',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='stock',
            new_name='producto_stock',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Telefono',
            new_name='proveedor_Telefono',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='direccion',
            new_name='proveedor_direccion',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='mail',
            new_name='proveedor_mail',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombre',
            new_name='proveedor_nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='productos',
            new_name='proveedor_productos',
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(),
        ),
    ]
