# Generated by Django 4.2.6 on 2023-10-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_categoria_productos_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='proveedor_Telefono',
            new_name='proveedor_telefono',
        ),
        migrations.AlterField(
            model_name='resena',
            name='nombre_de_cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptores',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
