# Generated by Django 4.2.6 on 2023-11-12 02:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_rename_proveedor_telefono_proveedor_proveedor_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='producto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_img'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto_descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_productos',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='resena',
            name='resena',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
