# Generated by Django 4.2.6 on 2023-11-12 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_productos_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='producto_fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
