# Generated by Django 4.2.6 on 2023-11-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_productos_producto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='proveedor_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
