# Generated by Django 4.2.6 on 2023-11-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_rename_producto_categoria_productos_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='fecha',
        ),
    ]
