# Generated by Django 4.2.6 on 2023-11-15 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_remove_productos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
