# Generated by Django 4.2.6 on 2023-11-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_productos_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='proveedor_direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='proveedor_mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='proveedor_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='proveedor_productos',
            new_name='productos',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='proveedor_telefono',
            new_name='telefono',
        ),
    ]
