# Generated by Django 4.2.6 on 2023-11-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='datos',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='provincia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
