# Generated by Django 4.2.6 on 2023-11-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_datos_avatar_alter_datos_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
