# Generated by Django 4.2.6 on 2023-11-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPerfil',
        ),
    ]
