# Generated by Django 4.2.6 on 2023-11-15 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0007_remove_datosextra_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='datosextra',
            name='ciudad',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='datosextra',
            name='direccion',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='datosextra',
            name='provincia',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='datosextra',
            name='telefono',
            field=models.IntegerField(default='-'),
        ),
        migrations.AddField(
            model_name='datosextra',
            name='user',
            field=models.OneToOneField(default='-', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
