# Generated by Django 4.2.6 on 2023-11-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_datosextra_avatar_datosextra_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='provincia',
            field=models.CharField(default='-2', max_length=100),
        ),
    ]
