# Generated by Django 4.2.6 on 2023-11-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_datosextra_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
