# Generated by Django 4.2.6 on 2023-11-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_datosextra_ciudad_alter_datosextra_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosextra',
            name='telefono',
        ),
    ]
