# Generated by Django 4.2.6 on 2023-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_datosextra_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
