# Generated by Django 4.2.6 on 2023-11-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_datosextra_telefono'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosExtra',
        ),
    ]
